on:
  pull_request:
  push:
    branches:
      - main

name: tests

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: no default features
        run: cargo test --no-default-features

      - name: default features
        run: cargo test --features codec

      - name: codec features
        run: cargo test --features codec

      - name: full features
        run: cargo test --features full

      - name: all features
        run: cargo test --all-features

